name: Cypress Tests

on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual trigger

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        browsers: [chrome, firefox, edge]
        spec:
          [
            cypress/e2e/login.cy.js,
            cypress/e2e/cart.cy.js,
            cypress/e2e/checkout.cy.js,
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Tests on ${{ matrix.browsers }} - ${{ matrix.spec }}
        run: npx cypress run --browser ${{ matrix.browsers }} --spec ${{ matrix.spec }} --env allure=true

      # Upload Cypress artifacts (screenshots/videos) if tests fail
      - name: Upload Test Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts-${{ matrix.browsers }}-${{ matrix.spec }}
          path: |
            cypress/screenshots
            cypress/videos

      # Generate Allure Report
      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
