name: Cypress Tests

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        browsers: [chrome, firefox, edge]
        spec:
          [
            cypress/e2e/login.cy.js,
            cypress/e2e/cart.cy.js,
            cypress/e2e/checkout.cy.js,
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run in ${{ matrix.browsers }}
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browsers }}
            - name: Upload Test Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts-${{ matrix.browser }}
          path: |
            cypress/screenshots
            cypress/videos